import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ExternalSiteCard from '@/common/ExternalSiteCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const externalWebsites = [
    {
      name:"Github",
      url:"https://github.com/NagumoSe",
      logo:"/GitHub-icon.png",
      imageAlt:"github logo"
    },
    {
      name:"Youtube",
      url:"://www.youtube.com/playlist?list=PLSK5TjaGbQfRT37kMSFshttpspWexml4CWBmoj",
      logo:"/youtube-icon.png",
      imageAlt:"youtube logo"
    },
    {
      name:"Instagram",
      url:"https://www.instagram.com/naji_gg/",
      logo:"/Instagram-icon.png",
      imageAlt:"instagram logo"
    }
  ]
  return (
    <>
      <Head>
        <title>first page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
           <div>
            <div>南雲 誠志（Nagumo,Seiji）</div>
            <div>2000年生まれ</div>
            <div>東京都出身</div>
            <div>長岡技術科学大学 情報・経営システム工学分野</div>
            <div>
            <a
                href="https://www.nagaokaut.ac.jp/j/nyuushi/gb/06_management/06_11.html"
                target="_brank"
                rel="noopener noreferrer"
              >
              知識システム研究室（湯川研）
            </a>
            </div>
           </div>
        </div>
        <div className={styles.center}>
          <Image
            // className={styles.logo}
            src="/36FD0A23-952E-41F7-93AD-D10DBEA5E0BB.jpg"
            alt="my grandmother"
            width={300}
            height={370}
            priority
          />
          <div className={styles.thirteen}>
           祖母
          </div>
        </div>

        <h2>外部リンク</h2>
        <div>
          {externalWebsites.map((website) => (
            <ExternalSiteCard
            siteName={website.name}
            siteUrl={website.url}
            siteIcon={website.logo}
            siteIconDescription={website.imageAlt}
            />
          ))}
        </div>
      </main>
    </>
  )
}
