import { useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import { Inter, The_Girl_Next_Door } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { finished } from "stream";

const inter = Inter({ subsets: ['latin'] })

export default function Todo() {

    const [todo,setTodo] = useState<string[]>([
        "就活",
        "研究",
        "英語勉強",
        "コード勉強",
        "強くなる",
        "論文調査",
    ]);
    const [inputItem,setInputItem] = useState<string>("");

    const finishedItem = (item: string) => {
        const newTodo = todo.filter((todo) => todo !==item);
        setTodo(newTodo);
    }
    const insertitem = () => {
        if(inputItem === "") return;
        const newTodo = todo.concat(inputItem);
        setTodo(newTodo);
        setInputItem("");
    }

    return (
        <>
        <Head>
            <title>first page</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    
        <main className={styles.main}>
            <h1>TODO リスト</h1>

            <div>
                <input type="text" placeholder="Todoを追加"
                onChange={(event) => setInputItem(event.target.value)}
                value={inputItem}
                />
                <button onClick={() => insertitem()}>追加</button>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>TODO</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {todo.map((item) => {
                        return (
                            <tr key={item}>
                                <td>{item}</td>
                                <td>
                                    <button onClick={() => finishedItem(item)}>完了</button>
                                </td>
                            </tr>
                        );
                    })}
                </tbody>
            </table>
        </main>
        </>
    );
}
